language: python
python:
    # supported python versions
    - "3.6"
    - "3.7"
    - "3.7-dev"  # 3.7 development branch
    # - "3.8-dev"  # 3.8 development branch
    # - "nightly"  # nightly build

# blocklist
branches:
  except:
  - dev
  # - nstarman

# # safelist
# branches:
#   only:
#   - master
#   - dev

before_install:
 # skip travis build if [skip travis] or [travis skip] in commit message
 # built into travis, but a good reminder
 - if git show -s HEAD | grep -F -q "[skip travis]" ; then echo "skip travis" && exit 0 ; fi
 - if git show -s HEAD | grep -F -q "[travis skip]" ; then echo "skip travis" && exit 0 ; fi


# command to install dependencies
install:
    - pip install -r requirements.txt
    - python setup.py install

# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script:
    - export PYTHONPATH=${PWD}/src:${PWD}  # needed to get astroPHD into path @TODO fix install
    - pytest tests/ # Only the astroPHD test files

notifications:
  email:
    recipients:
      - n.starkman@mail.utoronto.ca
    on_success: change
    on_failure: change
